--- Network strings

util.AddNetworkString("onFrameChange")
util.AddNetworkString("onSequenceChange")
util.AddNetworkString("onAngleChange")
util.AddNetworkString("onFrameNext")
util.AddNetworkString("onFramePrevious")
util.AddNetworkString("onFPSChange")
util.AddNetworkString("updateClientPosition")
util.AddNetworkString("removeClientAnimPuppeteer")
util.AddNetworkString("queryDefaultBonePoseOfPuppet")
util.AddNetworkString("queryNonPhysBonePoseOfPuppet")
util.AddNetworkString("onPoseParamChange")
util.AddNetworkString("onBoneFilterChange")
util.AddNetworkString("queryPhysObjects")
util.AddNetworkString("enablePuppeteerPlayback")
util.AddNetworkString("disablePuppeteerPlayback")
